In [7]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import joblib

In [5]:
class Perceptron:
    def __init__(self,eta,epochs):
        self.weights=np.random.randn(3)*(10**-4)
        print(f"self.weights:{self.weights}")
        self.eta=eta
        self.epochs=epochs

    def activationFunction(self,weights,inputs):
        z=np.dot(weights,inputs)
        return np.where(z>0,1,0)

    def fit(self,X,y):
        self.X=X
        self.y=y

        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X-with_bias:\n{X_with_bias}")

        for epoch in range(self.epochs):
            print(f"for epoch:{epoch}")
            y_hat=self.activationFunction(X_with_bias,self.weights)
            print(f"predicted value:\n{y_hat}")
            error=self.y-y_hat
            print(f"error: \n{error}")
            self.weights=self.weights+self.eta*np.dot(X_with_bias.T,error)
            print(f"updated weights:{self.weights}")   
    
    def predict(self,X):
        X_with_bias=np.c_[X,-np.ones((len(self.X),1))]
        return self.activationFunction(X_with_bias,self.weights)

AND opertation

In [8]:
Data={"X1":[0,0,1,1],"X2":[0,1,0,1],"y":[0,0,0,1]}
AND=pd.DataFrame(Data)
AND

X1  X2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [9]:
X=AND.drop("y",axis=1)
X

X1  X2
0   0   0
1   0   1
2   1   0
3   1   1

In [10]:
y=AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [11]:
model=Perceptron(0.5,10)
model.fit(X,y)

self.weights:[ 7.11019446e-05  6.47840461e-05 -1.43863591e-04]
X-with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch:0
predicted value:
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:[-0.4999289  -0.49993522  1.49985614]
for epoch:1
predicted value:
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:[7.11019446e-05 6.47840461e-05 9.99856136e-01]
for epoch:2
predicted value:
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:[0.5000711  0.50006478 0.49985614]
for epoch:3
predicted value:
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:[7.11019446e-05 6.47840461e-05 1.49985614e+00]
for epoch:4
predicted value:
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:[0.5000711  0.50006478 0.99985614]
for epoch:5
predicted value:
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64

In [14]:
model.predict(X)

array([0, 0, 0, 1])

In [15]:
model.weights

array([0.5000711 , 0.50006478, 0.99985614])